# PRAKTIKUM 4 - Klasifikasi dengan ANN

#### NAMA     : AHMED FATHIR SYAFAAT
#### KELAS    : TI - 3H
#### NIM      : 2241720083

Pada praktikum ini, Anda akan menggunakan library tensorflow dari google. Oleh karena itu, Anda diharuskan untuk menginstal tensorflow terlebih dahulu.

In [2]:
!pip install tensorflow

     ---------------------------------------- 0.0/48.7 kB ? eta -:--:--
     ------------------------------- ------ 41.0/48.7 kB 991.0 kB/s eta 0:00:01
     -------------------------------------- 48.7/48.7 kB 493.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/385.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/385.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/385.2 MB 2.0 MB/s eta 0:03:09
   ---------------------------------------- 0.0/385.2 MB 2.0 MB/s eta 0:03:09
   ---------------------------------------- 0.1/385.2 MB 469.7 kB/s eta 0:13:40
   ---------------------------------------- 0.1/385.2 MB 476.3 kB/s eta 0:13:29
   ---------------------------------------- 0.1/385.2 MB 476.3 kB/s eta 0:13:29
   ---------------------------------------- 0.1/385.2 MB 476.3 kB/s eta 0:13:29
   ---------------------------------------- 0.1/385.2 MB 476.3 kB/s eta 0:13:29
   ---------------------------------------- 0.1/385.2 MB 343.4 kB/s et

### Pra Pengolahan Data

#### Langkah 1 - Import Library

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

#### Langkah 2 - Load Data

In [3]:
dataset = pd.read_csv('assets/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


#### Langkah 3 - Encoding Data Kategorikal

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Langkah 5 - Split Data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#### Langkah 6 - Scaling Fitur

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Membuat Model ANN

#### Langkah 1 - Inisiasi Model ANN

In [11]:
ann = tf.keras.models.Sequential()

#### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Langkah 3 - Membuat Hidden Layer Kedua

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Langkah 4 - Membuat Output Layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training Model

#### Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Langkah 2 - Fitting Model

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 872us/step - accuracy: 0.7349 - loss: 0.5612
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7903 - loss: 0.4802
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.7911 - loss: 0.4559
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.7947 - loss: 0.4447
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - accuracy: 0.8177 - loss: 0.4165
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.8247 - loss: 0.4115
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.8234 - loss: 0.4153
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - accuracy: 0.8244 - loss: 0.4198
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8357 - loss: 0.3961
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - accuracy: 0.8343 - loss: 0.3947
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.8316 - loss: 0.4064
Epoch 12/100
250/25

### Membuat Prediksi

#### Modelkan Data Baru dan Buat Prediksi

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[False]]


#### Prediksi Dengan Data Testing

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#### Cek Akurasi dan Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1522   73]
 [ 200  205]]


0.8635